chat:
  enable-filter: false
  banned-words: []
  use-custom-format: true

blocks:
  enable-banned-blocks: true
  banned-blocks:
    - "TNT"

messages:
  custom-join-message: false
  custom-quit-message: false
