chat:
  enable-filter: false
  banned-words: []
  use-custom-format: true

blocks:
  enable-banned-blocks: true
  banned-blocks:
    - "TNT"

messages:
  custom-join-message: false
  custom-quit-message: false

# Database configuration
database:
  # MySQL configuration
  mysql:
    enabled: false
    host: localhost
    port: 3306
    database: minecraft
    username: root
    password: password
    prefix: core_

  # Auto-save interval in minutes
  auto-save-interval: 5
